# Generated by Django 5.1.4 on 2025-02-02 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_recording'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='guest_user_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
