# Generated by Django 5.1.4 on 2025-02-05 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0003_interview_guest_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interview',
            old_name='guest_user_id',
            new_name='guest_id',
        ),
    ]
