# Generated by Django 5.1.4 on 2025-02-09 16:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0004_rename_guest_user_id_interview_guest_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='candidate_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
