# Generated by Django 5.1.4 on 2025-02-13 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0005_interview_candidate_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='type',
            field=models.CharField(default='scheduled', max_length=20),
        ),
    ]
