# Generated by Django 5.1.4 on 2025-04-30 13:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0008_remove_city_country_remove_city_state_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=100)),
                ('required_employees', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('experience_level', models.CharField(choices=[('indifferent', 'Indifferent'), ('None', 'None'), ('Less than 1 year', 'Less than 1 year'), ('1-2 years', '1-2 years'), ('2-3 years', '2-3 years'), ('3-4 years', '3-4 years'), ('4-5 years', '4-5 years'), ('5-10 years', '5-10 years'), ('More than 10 years', 'More than 10 years')], max_length=50)),
                ('education_level', models.CharField(choices=[('indifferent', 'Indifferent'), ('high_school', 'High School'), ('bac', 'Bac'), ('bac+1', 'Bac +1'), ('bac+2', 'Bac +2'), ('bac+3', 'Bac +3'), ('bachelors', "Bachelor's Degree"), ('masters', "Master's Degree"), ('phd', 'Ph.D.')], max_length=50)),
                ('workplace', models.CharField(choices=[('on_site', 'On Site'), ('hybrid', 'Hybrid'), ('remote', 'Remote')], max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('published', 'Published'), ('fix', 'Needs Fix'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('contract_type', models.CharField(choices=[('indifferent', 'Indifferent'), ('permanent', 'Permanent'), ('fixed_term', 'Fixed Term'), ('training', 'Training'), ('pre_employment', 'Pre-employment'), ('full_time', 'Full-time'), ('part_time', 'Part-time'), ('freelance', 'Freelance')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_posts', to='users.company')),
                ('verified_by', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_job_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technical_skills', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('communication', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('problem_solving', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('teamwork', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('leadership', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('adaptability', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('work_ethic', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('creativity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='users.applicant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
