# Generated by Django 5.1.4 on 2024-12-27 19:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=100)),
                ('required_employees', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('experience_level', models.CharField(choices=[('indifferent', 'Indifferent'), ('None', 'None'), ('Less than 1 year', 'Less than 1 year'), ('1-2 years', '1-2 years'), ('2-3 years', '2-3 years'), ('3-4 years', '3-4 years'), ('4-5 years', '4-5 years'), ('5-10 years', '5-10 years'), ('More than 10 years', 'More than 10 years')], max_length=50)),
                ('education_level', models.CharField(choices=[('high_school', 'High School'), ('bachelors', "Bachelor's Degree"), ('bachelors + 1', "Bachelor's Degree + 1"), ('bachelors + 2', "Bachelor's Degree + 2"), ('bachelors + 3', "Bachelor's Degree + 3"), ('bachelors + 4', "Bachelor's Degree + 4"), ('bachelors + 5', "Bachelor's Degree + 5"), ('masters', "Master's Degree"), ('phd', 'Ph.D.')], max_length=50)),
                ('workplace', models.CharField(choices=[('on_site', 'On Site'), ('partly_from_home', 'Partly from Home'), ('mostly_from_home', 'Mostly from Home'), ('100%_from_home', '100% from Home')], max_length=50)),
                ('contract_type', models.CharField(choices=[('indifferent', 'Indifferent'), ('permanent', 'Permanent'), ('fixed_term', 'Fixed Term'), ('training', 'Training'), ('pre_employment', 'Pre-employment'), ('full_time', 'Full-time'), ('part_time', 'Part-time'), ('freelance', 'Freelance')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(help_text='Enter the job function', max_length=100, verbose_name='Job Function')),
                ('required_employees', models.IntegerField(help_text='Enter the number of employees needed', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Required Employees')),
                ('experience_level', models.CharField(choices=[('indifferent', 'Indifferent'), ('None', 'None'), ('Less than 1 year', 'Less than 1 year'), ('1-2 years', '1-2 years'), ('2-3 years', '2-3 years'), ('3-4 years', '3-4 years'), ('4-5 years', '4-5 years'), ('5-10 years', '5-10 years'), ('More than 10 years', 'More than 10 years')], help_text='Select the required experience level', max_length=50, verbose_name='Experience Level')),
                ('education_level', models.CharField(choices=[('high_school', 'High School'), ('bachelors', "Bachelor's Degree"), ('bachelors + 1', "Bachelor's Degree + 1"), ('bachelors + 2', "Bachelor's Degree + 2"), ('bachelors + 3', "Bachelor's Degree + 3"), ('bachelors + 4', "Bachelor's Degree + 4"), ('bachelors + 5', "Bachelor's Degree + 5"), ('masters', "Master's Degree"), ('phd', 'Ph.D.')], help_text='Select the required education level', max_length=50, verbose_name='Education Level')),
                ('workplace', models.CharField(choices=[('on_site', 'On Site'), ('partly_from_home', 'Partly from Home'), ('mostly_from_home', 'Mostly from Home'), ('100%_from_home', '100% from Home')], help_text='Select the workplace type', max_length=50, verbose_name='Workplace')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
                ('resume_file', models.FileField(upload_to='resumes/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
            ],
        ),
    ]
