# Generated by Django 5.1.4 on 2024-12-27 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='human_resources',
            field=models.ForeignKey(limit_choices_to={'user_type': 'human_resources'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='district_manager',
            field=models.ForeignKey(limit_choices_to={'user_type': 'district_manager'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='job_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobrequest'),
        ),
        migrations.AddField(
            model_name='resume',
            name='job_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobpost'),
        ),
    ]
