# Generated by Django 5.1.4 on 2025-02-24 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('candidate', 'Candidate'), ('super_candidate', 'Super Candidate'), ('hired', 'Hired'), ('rejected', 'Rejected'), ('contacted', 'Contacted')], default='pending', max_length=20),
        ),
    ]
