# Generated by Django 5.1.4 on 2025-01-08 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_rename_submitted_at_resume_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='hired_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
