# Generated by Django 5.1.4 on 2025-02-23 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_notification_entity_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='sender_email',
            field=models.EmailField(blank=True, help_text='Email of the sender when not an authenticated user', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='sender_name',
            field=models.CharField(blank=True, help_text='Name of the sender when not an authenticated user', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='sender_type',
            field=models.CharField(choices=[('user', 'Authenticated User'), ('applicant', 'Job Applicant'), ('system', 'System')], default='system', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='sender_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='entity_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
