# Generated by Django 5.1.4 on 2025-04-26 10:05

import django.db.models.deletion
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_notification_sender_email_notification_sender_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('preferred_industry', models.CharField(choices=[('manufacturing', 'Manufacturing'), ('technology', 'Technology'), ('healthcare', 'Healthcare'), ('retail', 'Retail'), ('finance', 'Finance'), ('education', 'Education'), ('services', 'Services'), ('other', 'Other')], max_length=100)),
                ('current_situation', models.CharField(choices=[('employed', 'Currently Employed'), ('open', 'Open for Jobs'), ('not_open', 'Not Open to Opportunities')], max_length=20)),
                ('post_level', models.CharField(choices=[('intern', 'Intern'), ('apprentice', 'Apprentice'), ('junior', 'Junior'), ('mid', 'Mid-Level'), ('senior', 'Senior'), ('lead', 'Team Lead'), ('manager', 'Manager')], max_length=20)),
                ('expected_salary', models.IntegerField()),
                ('availability_days', models.IntegerField(default=0, help_text='0 means immediate availability')),
                ('mobility', models.CharField(choices=[('international', 'International'), ('national', 'National'), ('regional', 'Regional')], max_length=20)),
                ('preferred_workplace', models.CharField(choices=[('remote', 'Remote'), ('hybrid', 'Hybrid'), ('onsite', 'On Site')], max_length=20)),
                ('years_of_experience', models.DecimalField(decimal_places=1, max_digits=4)),
                ('location', models.CharField(max_length=100)),
                ('resume_file', models.FileField(upload_to='resumes/', validators=[users.models.validate_pdf_extension])),
                ('military_service', models.BooleanField(default=False)),
                ('driving_license', models.BooleanField(default=False)),
                ('valid_passport', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('logo', models.ImageField(upload_to='company_logos/')),
                ('industry', models.CharField(choices=[('manufacturing', 'Manufacturing'), ('technology', 'Technology'), ('healthcare', 'Healthcare'), ('retail', 'Retail'), ('finance', 'Finance'), ('education', 'Education'), ('services', 'Services'), ('other', 'Other')], max_length=100)),
                ('size', models.CharField(choices=[('1-10', '1-10 employees'), ('11-50', '11-50 employees'), ('51-200', '51-200 employees'), ('201-500', '201-500 employees'), ('501+', '500+ employees')], max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=15)),
                ('website', models.URLField(blank=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('native_name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('esco_code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(max_length=50)),
                ('esco_code', models.CharField(max_length=50, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('company', 'Company'), ('applicant', 'Applicant')], max_length=20),
        ),
        migrations.CreateModel(
            name='ApplicantEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('degree_level', models.CharField(choices=[('secondary', 'Secondary'), ('terminal', 'Terminal'), ('bac', 'Bac'), ('ts', 'TS (Bac + 2)'), ('bac_3', 'Bac + 3'), ('bachelors', 'Bachelors'), ('master_1', 'Master 1'), ('master_2', 'Master 2'), ('phd', 'PhD'), ('certificate', 'Certificate'), ('no_degree', 'No Degree'), ('university_no_degree', 'University without Degree')], max_length=50)),
                ('school', models.CharField(max_length=100)),
                ('school_type', models.CharField(choices=[('university', 'University'), ('institute', 'Institute'), ('vocational', 'Vocational School'), ('high_school', 'High School'), ('other', 'Other')], max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='users.applicant')),
            ],
            options={
                'ordering': ['-end_date'],
            },
        ),
        migrations.CreateModel(
            name='ApplicantExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('industry', models.CharField(choices=[('manufacturing', 'Manufacturing'), ('technology', 'Technology'), ('healthcare', 'Healthcare'), ('retail', 'Retail'), ('finance', 'Finance'), ('education', 'Education'), ('services', 'Services'), ('other', 'Other')], max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='users.applicant')),
                ('occupation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experiences', to='users.occupation')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='applicant',
            name='preferred_occupation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interested_applicants', to='users.occupation'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='skills',
            field=models.ManyToManyField(related_name='applicants', to='users.skill'),
        ),
    ]
