# Generated by Django 5.1.4 on 2025-04-30 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_applicant_company_language_occupation_skill_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='language',
            name='native_name',
            field=models.CharField(max_length=100),
        ),
    ]
