# Generated by Django 5.1.4 on 2025-01-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_customuser_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneverification',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
