# Generated by Django 5.1.4 on 2025-04-30 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('users', '0008_remove_city_country_remove_city_state_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='location',
        ),
        migrations.AddField(
            model_name='applicant',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applicants', to='core.city'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applicants', to='core.country'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='languages',
            field=models.ManyToManyField(blank=True, related_name='applicants', to='core.language'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applicants', to='core.state'),
        ),
    ]
